name: x509csr
description: Create X.509 Certificate Signing Requests
version: 1.0.0
homepage: https://www.davidjanes.com
author: David Janes <davidjanes@davidjanes.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  asn1lib:
  pointycastle:
  basic_utils:

dev_dependencies:
  pedantic:
  test:
